package(default_visibility = ["//visibility:public"])

java_library(
  name = 'commons_lib',
  runtime_deps = [
    ':codec',
    ':io',
    ':lang',
  ],
)

java_library(
  name = 'codec',
  exports = ["@codec//jar"],
)

java_library(
  name = 'io',
  exports = ["@io//jar"],
)

java_library(
  name = 'lang',
  exports = ["@lang//jar"],
)
