include_defs('//bucklets/maven_jar.bucklet')

VER = '1.5.1'
REPO = MAVEN_CENTRAL

maven_jar(
  name = 'asciidoctorj',
  id = 'org.asciidoctor:asciidoctorj:' + VER,
  attach_source = False,
  repository = REPO,
  license = 'CC-BY3.0',
)
