package(default_visibility = ["//visibility:public"])

java_library(
  name = 'poi_lib',
  exports = [
    ':poi',
    ':poi-scratchpad',
  ],
)

java_library(
  name = 'poi',
  exports = ["@poi//jar"],
)

java_library(
  name = 'poi-scratchpad',
  exports = ["@poi-scratchpad//jar"],
)
