package(default_visibility = ["//visibility:public"])

java_library(
  name = 'xmlgraphics_lib',
  exports = [
    ':batik-anim',
    ':batik-awt-util',
    ':batik-bridge',
    ':batik-css',
    ':batik-dom',
    ':batik-ext',
    ':batik-extension',
    ':batik-gvt',
    ':batik-js',
    ':batik-parser',
    ':batik-script',
    ':batik-svg-dom',
    ':batik-svggen',
    ':batik-transcoder',
    ':batik-util',
    ':batik-xml',
    ':fop',
    ':xmlgraphics-commons',
  ],
)

java_library(
  name = 'batik-anim',
  exports = ["@batik-anim//jar"],
)

java_library(
  name = 'batik-awt-util',
  exports = ["@batik-awt-util//jar"],
)

java_library(
  name = 'batik-bridge',
  exports = ["@batik-bridge//jar"],
)
java_library(
  name = 'batik-css',
  exports = ["@batik-css//jar"],
)

java_library(
  name = 'batik-dom',
  exports = ["@batik-dom//jar"],
)

java_library(
  name = 'batik-ext',
  exports = ["@batik-ext//jar"],
)

java_library(
  name = 'batik-extension',
  exports = ["@batik-extension//jar"],
)

java_library(
  name = 'batik-gvt',
  exports = ["@batik-gvt//jar"],
)

java_library(
  name = 'batik-js',
  exports = ["@batik-js//jar"],
)

java_library(
  name = 'batik-parser',
  exports = ["@batik-parser//jar"],
)

java_library(
  name = 'batik-script',
  exports = ["@batik-script//jar"],
)

java_library(
  name = 'batik-svg-dom',
  exports = ["@batik-svg-dom//jar"],
)

java_library(
  name = 'batik-svggen',
  exports = ["@batik-svggen//jar"],
)

java_library(
  name = 'batik-transcoder',
  exports = ["@batik-transcoder//jar"],
)

java_library(
  name = 'batik-util',
  exports = ["@batik-util//jar"],
)

java_library(
  name = 'batik-xml',
  exports = ["@batik-xml//jar"],
)

java_library(
  name = 'fop',
  exports = ["@fop//jar"],
)

java_library(
  name = 'xmlgraphics-commons',
  exports = ["@xmlgraphics-commons//jar"],
)
