load("//tools/bzl:maven_jar.bzl", "maven_jar")

package(default_visibility = ["//visibility:public"])

java_library(
  name = 'xmlgraphics_lib',
  exports = [
    ':batik-anim',
    ':batik-awt-util',
    ':batik-bridge',
    ':batik-css',
    ':batik-dom',
    ':batik-ext',
    ':batik-extension',
    ':batik-gvt',
    ':batik-js',
    ':batik-parser',
    ':batik-script',
    ':batik-svg-dom',
    ':batik-svggen',
    ':batik-transcoder',
    ':batik-util',
    ':batik-xml',
    ':fop',
    ':xmlgraphics-commons',
  ],
)

maven_jar(
  name = 'batik-anim',
  artifact = 'org.apache.xmlgraphics:batik-anim:1.7',
  sha1 = 'a45dd2ff8e4ecd56a4fc64dc668b53bee90bf601',
  attach_source = False,
)

maven_jar(
  name = 'batik-awt-util',
  id = 'org.apache.xmlgraphics:batik-awt-util:1.7',
  sha1 = '67605a29d49bf33f3c1d7832f490b0a007e7a6e2',
  attach_source = False,
)

maven_jar(
  name = 'batik-bridge',
  artifact = 'org.apache.xmlgraphics:batik-bridge:1.7',
  sha1 = '8e0cde3830e0f17704cd392b0a09b13944987a51',
  attach_source = False,
)
maven_jar(
  name = 'batik-css',
  artifact = 'org.apache.xmlgraphics:batik-css:1.7',
  sha1 = 'e6bb5c85753331534593f33fb9236acb41a0ab79',
  attach_source = False,
)

maven_jar(
  name = 'batik-dom',
  artifact = 'org.apache.xmlgraphics:batik-dom:1.7',
  sha1 = '710d559bd1df52581b57b75a99ed5fd2e2918bb7',
  attach_source = False,
)

maven_jar(
  name = 'batik-ext',
  artifact = 'org.apache.xmlgraphics:batik-ext:1.7',
  sha1 = '4784302b44a0336166fef6153a5e3d73e861aecc',
  attach_source = False,
)

maven_jar(
  name = 'batik-extension',
  artifact = 'org.apache.xmlgraphics:batik-extension:1.7',
  sha1 = '8e810d9ce0499beca541e3b1a144557cf06f8b19',
  attach_source = False,
)

maven_jar(
  name = 'batik-gvt',
  id = 'org.apache.xmlgraphics:batik-gvt:1.7',
  sha1 = '03d315e60d72c761c52946b4acaa4b86239ef938',
  attach_source = False,
)

maven_jar(
  name = 'batik-js',
  artifact = 'org.apache.xmlgraphics:batik-js:1.7',
  sha1 = '688eb1bf13b7a54491fcb3405068fc5092589884',
  attach_source = False,
)

maven_jar(
  name = 'batik-parser',
  artifact = 'org.apache.xmlgraphics:batik-parser:1.7',
  sha1 = '5d756cc4f6bf891793e6c7590773859c33a8609f',
  attach_source = False,
)

maven_jar(
  name = 'batik-script',
  artifact = 'org.apache.xmlgraphics:batik-script:1.7',
  sha1 = '4ea7906724bfefc1fca3e5b28229a458523e1fbf',
  license = 'Apache2.0',
  attach_source = False,
)

maven_jar(
  name = 'batik-svg-dom',
  artifact = 'org.apache.xmlgraphics:batik-svg-dom:1.7',
  sha1 = '5b3b1fea480fabbd3e0c44540af25b9fda0587ae',
  attach_source = False,
)

maven_jar(
  name = 'batik-svggen',
  artifact = 'org.apache.xmlgraphics:batik-svggen:1.7',
  sha1 = 'baa58d0f5bfd2a28142e222cee126eb71bd0a938',
  attach_source = False,
)

maven_jar(
  name = 'batik-transcoder',
  artifact = 'org.apache.xmlgraphics:batik-transcoder:1.7',
  sha1 = 'aa2eb6300cb50bbb9dbf52daf7d625aa0df1d930',
  attach_source = False,
)

maven_jar(
  name = 'batik-util',
  artifact = 'org.apache.xmlgraphics:batik-util:1.7',
  sha1 = '5c4dd0dd9a86a2fba2c6ea26fb62b32b21b2a61e',
  attach_source = False,
)

maven_jar(
  name = 'batik-xml',
  artifact = 'org.apache.xmlgraphics:batik-xml:1.7',
  sha1 = '17e3da8bd9d4a131350a7835f5cc0d93ba199c89',
  attach_source = False,
)

maven_jar(
  name = 'fop',
  artifact = 'org.apache.xmlgraphics:fop:1.1',
  sha1 = '95978100a6cde324078947a2d476cf2f207a7e5a',
  attach_source = False,
)

maven_jar(
  name = 'xmlgraphics-commons',
  artifact = 'org.apache.xmlgraphics:xmlgraphics-commons:1.5',
  sha1 = '7fb5c2b2c18f0e87fbe9bded16429a5d7cc2dc2b',
  attach_source = False,
)
