package(default_visibility = ["//visibility:public"])

java_library(
  name = 'avalon-framework_lib',
  exports = [
    ':avalon-framework-api',
    ':avalon-framework-impl',
  ],
)

java_library(
  name = 'avalon-framework-api',
  exports = ["@avalon-framework-api//jar"],
)

java_library(
  name = 'avalon-framework-impl',
  exports = ["@avalon-framework-impl//jar"],
)
