include_defs('//bucklets/maven_jar.bucklet')

java_library(
  name = 'daisydiff_lib',
  exported_deps = [
    ':daisydiff',
  ],
  visibility = ['PUBLIC'],
)

maven_jar(
  name = 'daisydiff',
  id = 'org.outerj.daisy:daisydiff:1.1',
  sha1 = 'a67ed5147dd164e0614f1efc0145d06851c90d4f',
  repository = 'https://maven.atlassian.com/content/repositories/atlassian-3rdparty',
  license = 'Apache2.0',
  attach_source = False,
)
