package(default_visibility = ["//visibility:public"])

java_library(
  name = 'daisydiff_lib',
  exports = [
    ':daisydiff',
  ],
)

java_library(
  name = 'daisydiff',
  exports = ["@daisydiff//jar"],
)
