package(default_visibility = ["//visibility:public"])

java_library(
  name = 'plutext_lib',
  exports = [
    ':jaxb-svg11',
    ':jaxb-xmldsig-core',
    ':jaxb-xslfo',
  ],
)

java_library(
  name = 'jaxb-svg11',
  exports = ["@jaxb-svg11//jar"],
)

java_library(
  name = 'jaxb-xmldsig-core',
  exports = ["@jaxb-xmldsig-core//jar"],
)

java_library(
  name = 'jaxb-xslfo',
  exports = ["@jaxb-xslfo//jar"],
)
