package(default_visibility = ["//visibility:public"])

java_library(
  name = 'asciidoc_lib',
  exports = [
    ':asciidoctor',
    ':jruby',
  ],
)

java_library(
  name = 'asciidoctor',
  exports = ["@asciidoctor//jar"],
)

java_library(
  name = 'jruby',
  exports = ["@jruby//jar"],
)
